# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DB: nest-api-pokemon
    volumes:
      - ./mongo:/data/db
